"use client";
import { useActionState, useEffect, useState } from "react";
import { useFormStatus } from "react-dom";
import type { Configuration } from "@/modules/products/contracts";
import { Button } from "../ui";
import { saveConfiguration } from "./actions";
import styles from "./setup.module.css";
function PublishControls() { const {pending}=useFormStatus(); return <div className={styles.controls}><Button name="intent" value="save" className="secondary" disabled={pending}>Save draft</Button><Button name="intent" value="activate" disabled={pending}>{pending ? "Saving…" : "Activate product"}</Button></div>; }
export function ProductEditor({productId,versionId,revision,initialName,initial}:{productId:string;versionId:string;revision:number;initialName:string;initial:Configuration}) {
  const [configuration,setConfiguration]=useState(initial),[name,setName]=useState(initialName),[currentRevision,setRevision]=useState(revision);
  const [state,action]=useActionState(saveConfiguration,{});
  useEffect(()=>{if(state.revision!==undefined)setRevision(state.revision);},[state]);
  const normalize=(c:Configuration):Configuration=>({...c,inputs:c.inputs.map((r,i)=>({...r,sortOrder:i})),sections:c.sections.map((r,i)=>({...r,sortOrder:i}))});
  function move(kind:"inputs"|"sections",index:number,offset:number) { setConfiguration(c=>{const rows=[...c[kind]],target=index+offset;if(target<0||target>=rows.length)return c;[rows[index],rows[target]]=[rows[target],rows[index]];return normalize({...c,[kind]:rows});}); }
  const controls=(kind:"inputs"|"sections",index:number)=> <div className={styles.rowControls}><Button type="button" className="ghost" disabled={index===0} aria-label={(kind==="inputs"?"Field ":"Section ")+(index+1)+" move up"} onClick={()=>move(kind,index,-1)}>↑</Button><Button type="button" className="ghost" disabled={index===configuration[kind].length-1} aria-label={(kind==="inputs"?"Field ":"Section ")+(index+1)+" move down"} onClick={()=>move(kind,index,1)}>↓</Button><Button type="button" className="ghost" aria-label={(kind==="inputs"?"Field ":"Section ")+(index+1)+" remove"} onClick={()=>setConfiguration(c=>normalize({...c,[kind]:c[kind].filter((_,i)=>i!==index)}))}>Remove</Button></div>;
  return <form action={action} className={styles.editor}><input type="hidden" name="productId" value={productId}/><input type="hidden" name="versionId" value={versionId}/><input type="hidden" name="revision" value={currentRevision}/><input type="hidden" name="configuration" value={JSON.stringify(configuration)}/>
    <label>Product name<input name="name" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label>
    <section><div className={styles.sectionHeading}><h2>1. Customer information</h2><span className="small muted">Fields your customer should provide</span></div>
      <p className="small muted">Customer answers must match these field labels. Information we cannot match stays marked for review. Use YYYY-MM-DD for dates.</p>
      {configuration.inputs.map((field,index)=><div className={styles.definition} key={field.id}>{controls("inputs",index)}<div className={styles.fieldGrid}><label>Field {index+1} label<input maxLength={200} value={field.label} onChange={e=>setConfiguration(c=>({...c,inputs:c.inputs.map(f=>f.id===field.id?{...f,label:e.target.value}:f)}))}/></label><label>Field {index+1} type<select value={field.type} onChange={e=>setConfiguration(c=>({...c,inputs:c.inputs.map(f=>f.id===field.id?{...f,type:e.target.value as typeof field.type}:f)}))}><option value="TEXT">Text</option><option value="LONG_TEXT">Long text</option><option value="DATE">Date</option></select></label></div><label className="check"><input type="checkbox" checked={field.required} onChange={e=>setConfiguration(c=>({...c,inputs:c.inputs.map(f=>f.id===field.id?{...f,required:e.target.checked}:f)}))}/>Required customer information</label><label>Field {index+1} help text<input maxLength={500} value={field.helpText} onChange={e=>setConfiguration(c=>({...c,inputs:c.inputs.map(f=>f.id===field.id?{...f,helpText:e.target.value}:f)}))}/></label></div>)}
      <Button type="button" className="secondary" disabled={configuration.inputs.length>=20} onClick={()=>{const id=crypto.randomUUID();setConfiguration(c=>({...c,inputs:[...c.inputs,{id,key:"input_"+id.replaceAll("-",""),label:"",type:"TEXT",required:true,helpText:"",sortOrder:c.inputs.length}]}));}}>Add customer field</Button>
    </section>
    <section><h2>2. Content structure</h2><p className="small muted">Define sections and short instructions. No content is created by this setup.</p>{configuration.sections.map((section,index)=><div className={styles.definition} key={section.id}>{controls("sections",index)}<label>Section {index+1} title<input maxLength={200} value={section.title} onChange={e=>setConfiguration(c=>({...c,sections:c.sections.map(s=>s.id===section.id?{...s,title:e.target.value}:s)}))}/></label><label>Section {index+1} instruction<textarea maxLength={2000} rows={2} value={section.instruction} onChange={e=>setConfiguration(c=>({...c,sections:c.sections.map(s=>s.id===section.id?{...s,instruction:e.target.value}:s)}))}/></label></div>)}<Button type="button" className="secondary" disabled={configuration.sections.length>=20} onClick={()=>setConfiguration(c=>({...c,sections:[...c.sections,{id:crypto.randomUUID(),title:"",instruction:"",sortOrder:c.sections.length}]}))}>Add content section</Button></section>
    <div className={styles.fieldGrid}><section><h2>3. Output</h2><label>Output format<select value={configuration.output??""} onChange={e=>setConfiguration(c=>({...c,output:e.target.value as Configuration["output"]}))}><option value="" disabled>Choose format</option><option value="TEXT">Text</option><option value="PDF">PDF</option></select></label><p className="small muted">Format preference only. PDF rendering is not available yet.</p></section><section><h2>4. Workflow</h2><label>Workflow mode<select value={configuration.workflow??""} onChange={e=>setConfiguration(c=>({...c,workflow:e.target.value as Configuration["workflow"]}))}><option value="" disabled>Choose workflow</option><option value="MANUAL">Manual</option><option value="ASSISTED">Assisted</option><option value="AUTOMATIC" disabled>Automatic — coming later</option></select></label><p className="small muted">Manual and Assisted save your intended workflow. Creation and sending are not enabled.</p></section></div>
    {state.error&&<p role="alert" className="error-message">{state.error}</p>}{state.saved&&<p role="status" className="notice">Draft saved. Saving does not activate your changes.</p>}{state.activated ? <p role="status" className="notice">Product activated. This configuration applies to new orders; content creation remains unavailable.</p> : <PublishControls/>}
  </form>;
}
