import Link from "next/link";
import { Badge } from "@/components/ui";
import { Icon } from "@/components/icon";
import styles from "./entry.module.css";
export function Landing() {
  return <div className={styles.landing}>
    <header className={styles.header}><Link href="/" className="wordmark">Reading<span>OS</span></Link><nav aria-label="Product"><a href="#how-it-works">How it works</a><a href="#features">Features</a><a href="#security">Security</a></nav><div className={styles.headerActions}><Link href="/sign-in" className="button ghost">Log in</Link><Link href="/sign-up" className="button">Get started</Link></div></header>
    <main><section className={styles.hero}><div><p className={styles.eyebrow}>Built for Etsy reading sellers</p><h1>Run your Etsy reading shop<br/>without the repetitive work.</h1><p className={styles.heroCopy}>Reading OS turns your Etsy orders into an organized workflow for creating personalized readings — from customer information to review and delivery.</p><div className={styles.ctas}><Link className="button" href="/sign-up">Get started<Icon name="arrow"/></Link><a className="button secondary" href="#how-it-works">See how it works</a></div><p className={styles.note}>Start with secure shop connection and organized orders. Creation, review and sending workflows are coming next.</p></div><div className={styles.preview} aria-label="Illustrative order workspace"><header><Icon name="orders"/><strong>Your order workspace</strong><span>Preview</span></header><div className={styles.previewHeading}><h2>Orders, with a clear next step.</h2><p>One checkout. Every reading accounted for.</p></div><article><div><strong>Taylor Reed</strong><span>Order #2002 · 3 readings</span></div><Badge tone="warning">Needs information</Badge></article><div className={styles.previewProducts}><span>Love Reading ×2</span><span>Career Reading ×1</span></div><article><div><strong>Customer information</strong><span>Spot missing details before starting a reading.</span></div><Icon name="arrow"/></article><footer>Illustrative workflow · not live customer data</footer></div></section>
    <section id="how-it-works" className={styles.section}><p className={styles.eyebrow}>A clearer way to work</p><h2>From Etsy order to your next action.</h2><ol className={styles.steps}>{[{title:"Connect Etsy",copy:"Authorize read-only access to your shop. You stay in control."},{title:"Choose products",copy:"Select the listings you want to set up in Reading OS."},{title:"Receive organized orders",copy:"See each purchase and the customer information it needs."},{title:"Create, review and send",copy:"The next stages of your reading workflow, coming later."}].map((step,i)=><li key={step.title}><span>{i+1}</span><h3>{step.title}</h3><p>{step.copy}</p></li>)}</ol></section>
    <section id="features" className={styles.section}><p className={styles.eyebrow}>Built for daily operations</p><h2>Your shop's work, in one place.</h2><div className={styles.features}><div><h3>A practical order queue</h3><p>Find orders, see purchased readings and resolve missing information.</p></div><div><h3>Every reading stays distinct</h3><p>Multiple products and quantities stay organized inside one customer order.</p></div><div><h3>Work from your phone</h3><p>Review orders and customer details without returning to a desktop.</p></div></div></section>
    <section id="security" className={`${styles.section} ${styles.security}`}><div><p className={styles.eyebrow}>Your shop, your control</p><h2>Clear permissions. Secure connection.</h2><p>Read-only Etsy access imports shop information, listings and relevant orders. Reading OS cannot edit your listings, issue refunds or change your shop settings through this connection.</p></div><ul><li>Authorize securely on Etsy</li><li>No Etsy password shared with Reading OS</li><li>Disconnect anytime; revoke access in Etsy settings</li></ul></section></main>
    <footer className={styles.footer}><span>Reading OS · Seller operations</span><p>The term ‘Etsy’ is a trademark of Etsy, Inc. This application uses the Etsy API but is not endorsed or certified by Etsy, Inc.</p></footer>
  </div>;
}
