import { database } from "@/db/client";
import { currentScope } from "@/modules/identity/session";
import { workspaceData } from "@/modules/intake/service";
import { Heading, Badge, EmptyState } from "@/components/ui";
import { ActionForm } from "@/components/submit";
import { Icon } from "@/components/icon";
import { saveMapping } from "@/app/actions";
export default async function ProductsPage() {
  const data = await workspaceData(database(), await currentScope());
  return <><Heading title="Products" description="Set up your Etsy products so each order has the right customer information." /><div className="product-list">{data.listings.map(listing=>{
    const variants=[...new Set(["default",...data.lines.filter(l=>l.listingExternalId===listing.externalId).map(l=>l.variantKey)])], configured=variants.map(v=>data.mappings.find(m=>m.listingExternalId===listing.externalId&&m.variantKey===v)), missing=configured.some(m=>!m),paused=configured.some(m=>m?.paused),status=missing ? "Setup required" : paused ? "Paused" : "Ready";
    return <article className="product-record" key={listing.id} id={`product-${listing.externalId}`}><div className="product-summary"><div className="product-thumbnail"><Icon name="image" width="24" height="24"/></div><div className="product-title"><h2>{listing.title}</h2><span className="muted small">Etsy · {listing.state}</span></div><Badge tone={status === "Ready" ? "good" : "warning"}>{status}</Badge></div><details className="product-setup"><summary>{missing ? "Set up" : "Edit"}<span className="sr-only"> {listing.title}</span></summary><div className="setup-body"><h3>Set up product</h3><ol className="wizard-steps"><li>Basics</li><li aria-current="step">Customer information</li><li>Reading <small>Later</small></li><li>Output <small>Later</small></li><li>Delivery <small>Later</small></li></ol><p className="small muted">For now, setup uses the customer questions on your Etsy listing. Reading creation, documents and sending are coming later.</p><h3>Customer information</h3><p>{listing.snapshot.personalization.filter(q=>q.required).map(q=>q.label).join(", ") || "No required customer questions on this listing."}</p>{variants.map(variant=>{const mapping=data.mappings.find(m=>m.listingExternalId===listing.externalId&&m.variantKey===variant),line=data.lines.find(l=>l.listingExternalId===listing.externalId&&l.variantKey===variant),label=variant === "default" ? "Standard purchase" : line?.snapshot.variations.map(v=>`${v.label}: ${v.value}`).join(" · ") || "Purchased option";return <div className="mapping-row" key={variant}><div><strong>{label}</strong><p className="muted small">{!mapping ? "Setup required" : mapping.paused ? "Paused" : "Ready"}</p>{variant!=="default"&&<details className="advanced-details"><summary>Variant settings</summary><p className="small muted">Etsy variant reference: {variant}. Each purchased option is set up separately.</p></details>}</div><ActionForm action={saveMapping} label={!mapping ? "Save product setup" : mapping.paused ? "Resume product" : "Pause product"} secondary={!!mapping}><input type="hidden" name="listingId" value={listing.externalId}/><input type="hidden" name="variantKey" value={variant}/><input type="hidden" name="paused" value={mapping&&!mapping.paused ? "true" : "false"}/></ActionForm></div>;})}<details className="advanced-details"><summary>Advanced details</summary><p className="small muted">Etsy listing #{listing.externalId}. Setup does not edit your Etsy listing. Paused products remain visible on existing orders.</p></details></div></details></article>;
  })}</div>{!data.listings.length&&<EmptyState title="No products yet" href="/settings" action="Open settings">Connect your store and update your Etsy listings to get started.</EmptyState>}</>;
}
